Update to 1.532.1
Changelog:
What's new in 1.532.1 (2013/11/25)

    Collecting findbugs analysis results occasionally causes ssh slave to go offline causing job to abort (issue 19619)
    Bytecode compatibility transformer mistakenly corrupts org.apache.ivy.core.settings.IvySettings.triggers (issue 19383)
    Functions.globalIota overflow (issue 20085)
    Upgrade bundled versions of credentials, ssh-credentials and ssh-slaves plugins (issue 19945)
    /me/my-views/editDescription may be used by any user to set global description (issue 18633)
    Missing base directory in ZIP from .../artifact/dir/subdir/*zip*/subdir.zip (issue 19947)
    After deleting last build, next build of last build is zombie (issue 19920)
    Upgrade error to 1.531: PROXY_HEADER is null (issue 19613)
    Upgrade bundled versions of credentials and ssh-slaves so we can assume available (issue 20071)
    Collecting finbugs analysis results randomly fails with exception (issue 18879)
    ViewJobFilter.filter expect "All jobs that are possible." but don't get recursive ones (issue 20143)
    Download build artifacts as zip generates a corrupted file (issue 19752)
    Jenkins redirecting from https to http (issue 10675)
    java.io.IOException: Unexpected termination of the channel (issue 18836)
    When installing a plugin and the needed dependencies have compatibility issues, warn the user (issue 19739)
    Installing a plugin with optional dependencies doesn't upgrade the optional dependencies when needed (issue 19736)
    After upgrade from 1.519 to 1.526 -> NumberFormatException occurs during maven 3 build (issue 19251)


What's new in 1.509.4 (2013/10/09)

    Configurable loggers should capture messages on slaves (issue 18274)
    @RequirePOST and similar should send a 405 (issue 16918)
    Using jenkins-cli connecting to HTTPS port fails due to hostname mismatch in certificate (issue 12629)
    [XStream] ConcurrentModificationException from DefaultConverterLookup (issue 18775)
    @QueryParameter with @RelativePath broken (issue 18776)
    fingerprint are truncated (issue 19515)
    Environment variable replacement/resolving (issue 16660)
    failed to archive slave artifacts. Unexpected end of ZLIB input stream (issue 19473)
    winstone.ClientSocketException: Failed to write to client (issue 10524)
    /log/all polluted with FINE* messages from other loggers (issue 18959)
    Incorrect redirect after editing view with Unicode name (issue 18373)
    Flyweight jobs and zero executors (issue 7291)
    ERR_CONTENT_DECODING_FAILED on Custom Views with Project-based Matrix Authorization (issue 15437)
    Buttons do not work in IE 11 (issue 19171)
    CLI login command fails on Windows (issue 19192)
    Problems with "Latest Test Result" and "Aggregated Test Result" links (issue 9637)
    Exception while trigger downstream projects (issue 17247)
    Maven 2 jobs fail (exception in MavenFingerprinter) (issue 18441)
    Outdated JRuby libs (issue 14351)
    Deadlock (issue 18589)
    When copying folder, display names of contained jobs are gratuitously cleared (issue 18074)
    Incorrect redirection after delete of job in folder in view (issue 17575)
    Javadoc project action yields HTTP 404 (issue 19168)
    Memory exhaustion parsing large test stdio from Surefire (issue 15382)
    With lazy-build loading estimated build duration may become expensive (issue 18196)
    Can't build using maven 3.1.0 (issue 15935)
    Cannot create a custom logger matching any namespace (issue 17983)
    Clean up fingerprint records that correspond to the deleted build recods (issue 18417)
    "projects tied to slave" shows unrelated maven module jobs (issue 17451)
    hudson.security.AccessDeniedException2: anonymous is missing the Administer permission (issue 15578)
    ”My Views" links leads to 404 Not Found (issue 17317)
    Some jobs not loaded after jenkins restart: java.lang.NoSuchFieldError: triggers (issue 18677)
    New lazy loading permalinks can break job.lastStableBuild != null => job.lastSuccessfulBuild != null (issue 18846)