Update to 1.9.1:
* Fix python code to work with python-3
* Security fix for integer overflow in read_packet() [CVE-2013-2064]

Alan Coopersmith (2):
      integer overflow in read_packet() [CVE-2013-2064]
      libxcb 1.9.1

Christian König (1):
      whitespace fix in xcb_take_socket

Chí-Thanh Christopher Nguyễn (2):
      c-client.py: Fix python-3 AttributeError: 'dict' object has no attribute 'iteritems'
      c_client.py: Fix python-3 invalid except statement

Colin Walters (1):
      autogen.sh: Implement GNOME Build API